config:
  validation: true
  warningsAsErrors: false

formatting:
  active: true
  autoCorrect: false
  MaximumLineLength:
    maxLineLength: 120

style:
  active: true
  MagicNumber:
    active: false
  ReturnCount:
    max: 3
  ForbiddenComment:
    active: false

complexity:
  active: true
  LongParameterList:
    functionThreshold: 8
    constructorThreshold: 8
  TooManyFunctions:
    thresholdInFiles: 20
    thresholdInClasses: 15

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  RedundantSuspendModifier:
    active: true
  SleepInsteadOfDelay:
    active: true
  SuspendFunWithFlowReturnType:
    active: true

naming:
  active: true
  FunctionNaming:
    functionPattern: '[a-z][a-zA-Z0-9]*'
    excludes: ['**/test/**', '**/Test*']

comments:
  active: false
